const MENU_MASTERS = [
  { id: 'super-categories', label: 'Super Categories', href: 'super-categories.html' },
  { id: 'categories', label: 'Categories', href: 'categories.html' },
  { id: 'sub-categories', label: 'Sub-Categories', href: 'sub-categories.html' },
  { id: 'items', label: 'Items', href: 'items.html' },
  { id: 'addons', label: 'Addons', href: 'addons.html' },
  { id: 'variants', label: 'Variants', href: 'variants.html' },
  { id: 'submenu', label: 'Submenu', href: 'submenu.html' },
];

const CATEGORIES_DATA = [
  { name: 'Maggi - DM', onlineDisplayName: '--', itemCount: 5 },
  { name: 'Sides - DM', onlineDisplayName: '--', itemCount: 5 },
  { name: 'Drinks - DM', onlineDisplayName: '--', itemCount: 10 },
  { name: 'Ultimate Combos - DM', onlineDisplayName: '--', itemCount: 3 },
  { name: 'Extras - DM', onlineDisplayName: '--', itemCount: 3 },
  { name: 'Add Ons - DM', onlineDisplayName: '--', itemCount: 14 },
  { name: 'FLavours of Amritsar', onlineDisplayName: '--', itemCount: 2 },
  { name: 'Sugran Starters', onlineDisplayName: 'Sugran Starters', itemCount: 1 },
  { name: 'Starters - S', onlineDisplayName: 'Starters', itemCount: 14 },
  { name: 'Main Course Non-Veg - S', onlineDisplayName: 'Main Course Non-Veg', itemCount: 8 },
  { name: 'Rice - S', onlineDisplayName: 'Rice.', itemCount: 4 },
  { name: 'Bhakri - S', onlineDisplayName: 'Bhakri', itemCount: 3 },
  { name: 'Drink - S', onlineDisplayName: 'Drink', itemCount: 5 },
  { name: 'Thalis - S', onlineDisplayName: 'Thalis', itemCount: 8 },
  { name: 'Main Course Veg - S', onlineDisplayName: 'Main Course Veg', itemCount: 23 },
  { name: 'Tea And Snacks', onlineDisplayName: '--', itemCount: 12 },
  { name: 'Coffee House - A', onlineDisplayName: '--', itemCount: 7 },
  { name: 'Karnataka Bhel House - A', onlineDisplayName: '--', itemCount: 4 },
  { name: 'ICE CREAM - A', onlineDisplayName: '--', itemCount: 17 },
  { name: 'Veg Curry', onlineDisplayName: '--', itemCount: 86 },
  { name: 'Breads', onlineDisplayName: '--', itemCount: 18 },
  { name: 'Pilot Chef - A', onlineDisplayName: '--', itemCount: 2 },
  { name: 'Mocktail Bar', onlineDisplayName: '--', itemCount: 18 },
  { name: 'Papadum & Salad', onlineDisplayName: '--', itemCount: 5 },
  { name: 'Tandoori Starters', onlineDisplayName: '--', itemCount: 15 },
  { name: 'Thali', onlineDisplayName: '--', itemCount: 5 },
  { name: 'Roti / Paratha', onlineDisplayName: '--', itemCount: 10 },
  { name: 'Shakes', onlineDisplayName: '--', itemCount: 5 },
  { name: 'Desserts', onlineDisplayName: '--', itemCount: 6 },
  { name: 'Main Course', onlineDisplayName: '--', itemCount: 25 },
  { name: 'Tandoori Handi', onlineDisplayName: '--', itemCount: 4 },
  { name: 'Dal', onlineDisplayName: '--', itemCount: 5 },
  { name: 'Rice / Pulao', onlineDisplayName: '--', itemCount: 11 },
  { name: 'Raita', onlineDisplayName: '--', itemCount: 5 },
  { name: 'Chinese Maincourse', onlineDisplayName: '--', itemCount: 9 },
  { name: 'Rice', onlineDisplayName: '--', itemCount: 5 },
  { name: 'Noodles', onlineDisplayName: '--', itemCount: 3 },
  { name: 'Indian Breads', onlineDisplayName: '--', itemCount: 107 },
  { name: 'Tandoori Platers', onlineDisplayName: '--', itemCount: 3 },
  { name: 'Tiffin', onlineDisplayName: 'Tiffein', itemCount: 0 },
  { name: 'Burger -N', onlineDisplayName: '--', itemCount: 31 },
  { name: 'Wraps -N', onlineDisplayName: '--', itemCount: 26 },
  { name: 'Pasta -N', onlineDisplayName: '--', itemCount: 7 },
  { name: 'Dips -N', onlineDisplayName: '--', itemCount: 7 },
  { name: 'Sandwich -N', onlineDisplayName: '--', itemCount: 22 },
  { name: 'Snacks -N', onlineDisplayName: '--', itemCount: 11 },
  { name: 'Momos -N', onlineDisplayName: '--', itemCount: 8 },
  { name: 'Garlic Bread -N', onlineDisplayName: '--', itemCount: 3 },
  { name: 'Real Fruit Smoothies -N', onlineDisplayName: '--', itemCount: 5 },
  { name: 'Non Veg Snacks -N', onlineDisplayName: '--', itemCount: 18 },
];

const SUB_CATEGORIES_DATA = [
  { name: 'Double scoop', category: 'ICE CREAM - A' },
  { name: 'BURGERS', category: 'Pilot Chef - A' },
  { name: 'PASTA', category: 'Pilot Chef - A' },
  { name: 'MAGGIE', category: 'Pilot Chef - A' },
  { name: 'MOMOS', category: 'Pilot Chef - A' },
  { name: 'STARTERS', category: 'Pilot Chef - A' },
  { name: 'CHINESE', category: 'Pilot Chef - A' },
  { name: 'RICE BOWLS', category: 'Pilot Chef - A' },
  { name: 'DESSERTS', category: 'Pilot Chef - A' },
  { name: 'NACHOS', category: 'Pilot Chef - A' },
  { name: 'SANDWITCHES', category: 'Pilot Chef - A' },
  { name: 'COLD BEVERAGES', category: 'Pilot Chef - A' },
  { name: 'Veg Burger', category: 'Burger - N' },
  { name: 'Veg Wraps', category: 'Wraps - N' },
  { name: 'Veg Pasta', category: 'Pasta - N' },
  { name: 'Non-Veg Pasta', category: 'Pasta - N' },
  { name: 'Veg Sandwich', category: 'Sandwich - N' },
  { name: 'Non-Veg Sandwich', category: 'Sandwich - N' },
  { name: 'Pizza', category: 'QSR' },
  { name: 'Chinese', category: 'QSR' },
  { name: 'Burger', category: 'QSR' },
  { name: 'Fine Dine Veg', category: 'Fine Dine' },
];

const ITEMS_DATA = [
  { name: 'French Fries Peri - Peri - Z', displayName: 'French Fries Peri - Peri', category: 'Blue Valley Special - Z', shortCode: '--', basePrice: 180, tax: 'GST 0%', mrp: 180 },
  { name: 'Roti Basket Tokri - Z', displayName: 'Roti Basket Tokri', category: 'Roti - Z', shortCode: '--', basePrice: 250, tax: 'GST 0%', mrp: 250 },
  { name: 'Kashmiri Naan - Z', displayName: 'Kashmiri Naan', category: 'Roti - Z', shortCode: '--', basePrice: 100, tax: 'GST 0%', mrp: 100 },
  { name: 'Cheese Garlic Naan - Z', displayName: 'Cheese Garlic Naan', category: 'Roti - Z', shortCode: '--', basePrice: 120, tax: 'GST 0%', mrp: 120 },
  { name: 'Cheese Naan - Z', displayName: 'Cheese Naan', category: 'Roti - Z', shortCode: '--', basePrice: 100, tax: 'GST 0%', mrp: 100 },
  { name: 'Stuffed Naan - Z', displayName: 'Stuffed Naan', category: 'Roti - Z', shortCode: '--', basePrice: 100, tax: 'GST 0%', mrp: 100 },
  { name: 'Paneer Paratha - Z', displayName: 'Paneer Paratha', category: 'Roti - Z', shortCode: '--', basePrice: 150, tax: 'GST 0%', mrp: 150 },
  { name: 'Garlic Naan - Z', displayName: 'Garlic Naan', category: 'Roti - Z', shortCode: '--', basePrice: 120, tax: 'GST 0%', mrp: 120 },
  { name: 'Butter Naan - Z', displayName: 'Butter Naan', category: 'Roti - Z', shortCode: '--', basePrice: 70, tax: 'GST 0%', mrp: 70 },
  { name: 'Stuffed Kulcha - Z', displayName: 'Stuffed Kulcha', category: 'Roti - Z', shortCode: '--', basePrice: 100, tax: 'GST 0%', mrp: 100 },
  { name: 'Aloo Paratha - Z', displayName: 'Aloo Paratha', category: 'Roti - Z', shortCode: '--', basePrice: 120, tax: 'GST 0%', mrp: 120 },
  { name: 'Lachcha Paratha - Z', displayName: 'Lachcha Paratha', category: 'Roti - Z', shortCode: '--', basePrice: 70, tax: 'GST 0%', mrp: 70 },
  { name: 'Plain Naan - Z', displayName: 'Plain Naan', category: 'Roti - Z', shortCode: '--', basePrice: 60, tax: 'GST 0%', mrp: 60 },
  { name: 'Missi Roti - Z', displayName: 'Missi Roti', category: 'Roti - Z', shortCode: '--', basePrice: 50, tax: 'GST 0%', mrp: 50 },
  { name: 'Tandoori Butter - Z', displayName: 'Tandoori Butter', category: 'Roti - Z', shortCode: '--', basePrice: 20, tax: 'GST 0%', mrp: 20 },
  { name: 'Paneer Tufani - Z', displayName: 'Paneer Tufani', category: 'Blue Valley Special - Z', shortCode: '--', basePrice: 270, tax: 'GST 0%', mrp: 270 },
  { name: 'Paneer Kaleji - Z', displayName: 'Paneer Kaleji', category: 'Blue Valley Special - Z', shortCode: '--', basePrice: 270, tax: 'GST 0%', mrp: 270 },
  { name: 'Mashroom Paneer Masala - Z', displayName: 'Mashroom Paneer Masala', category: 'Blue Valley Special - Z', shortCode: '--', basePrice: 270, tax: 'GST 0%', mrp: 270 },
  { name: 'Paneer Masala - Z', displayName: 'Paneer Masala', category: 'Rice - Z', shortCode: '--', basePrice: 200, tax: 'GST 0%', mrp: 200 },
  { name: 'Hyderabadi Biryani - Z', displayName: 'Hyderabadi Biryani', category: 'Rice - Z', shortCode: '--', basePrice: 190, tax: 'GST 0%', mrp: 190 },
  { name: 'Masala Pulav - Z', displayName: 'Masala Pulav', category: 'Rice - Z', shortCode: '--', basePrice: 130, tax: 'GST 0%', mrp: 130 },
  { name: 'Matar Pulav - Z', displayName: 'Matar Pulav', category: 'Rice - Z', shortCode: '--', basePrice: 120, tax: 'GST 0%', mrp: 120 },
  { name: 'Jeera Rice - Z', displayName: 'Jeera Rice', category: 'Rice - Z', shortCode: '--', basePrice: 110, tax: 'GST 0%', mrp: 110 },
  { name: 'Plain Rice - Z', displayName: 'Plain Rice', category: 'Rice - Z', shortCode: '--', basePrice: 100, tax: 'GST 0%', mrp: 100 },
  { name: 'Bisleri Cold Drink - Z', displayName: 'Bisleri Cold Drink', category: 'Ice Cream + Shake - Z', shortCode: '--', basePrice: 140, tax: 'GST 0%', mrp: 140 },
  { name: 'Cold Coffee With Ice Cream - Z', displayName: 'Cold Coffee With Ice Cream', category: 'Ice Cream + Shake - Z', shortCode: '--', basePrice: 120, tax: 'GST 0%', mrp: 120 },
  { name: 'Mango Shake - Z', displayName: 'Mango Shake', category: 'Ice Cream + Shake - Z', shortCode: '--', basePrice: 120, tax: 'GST 0%', mrp: 120 },
  { name: 'Strawberry Shake - Z', displayName: 'Strawberry Shake', category: 'Ice Cream + Shake - Z', shortCode: '--', basePrice: 120, tax: 'GST 0%', mrp: 120 },
  { name: 'Chocolate Shake - Z', displayName: 'Chocolate Shake', category: 'Ice Cream + Shake - Z', shortCode: '--', basePrice: 120, tax: 'GST 0%', mrp: 120 },
  { name: 'Vanilla Shake - Z', displayName: 'Vanilla Shake', category: 'Ice Cream + Shake - Z', shortCode: '--', basePrice: 100, tax: 'GST 0%', mrp: 100 },
  { name: 'Cold Coffee - Z', displayName: 'Cold Coffee', category: 'Ice Cream + Shake - Z', shortCode: '--', basePrice: 100, tax: 'GST 0%', mrp: 100 },
  { name: 'Virgin Mojito - Z', displayName: 'Virgin Mojito', category: 'Ice Cream + Shake - Z', shortCode: '--', basePrice: 80, tax: 'GST 0%', mrp: 80 },
  { name: 'Fresh Lemon Soda - Z', displayName: 'Fresh Lemon Soda', category: 'Ice Cream + Shake - Z', shortCode: '--', basePrice: 60, tax: 'GST 0%', mrp: 60 },
  { name: 'Rajbhag Ice Cream - Z', displayName: 'Rajbhag Ice Cream', category: 'Ice Cream + Shake - Z', shortCode: '--', basePrice: 80, tax: 'GST 0%', mrp: 80 },
];

const ADDONS_DATA = [
  { name: 'Adventure4', displayName: 'Upgrade Combo', items: 'Add 2 French Fries 160/- - DM, All Paneer Momos 30/- - DM' },
  { name: 'Adventure2', displayName: 'Select One', items: '8Pcs Pan Tossed Momos - DM, 8Pcs Tandoori Momos - DM' },
  { name: 'Me time bites', displayName: 'Add Ons', items: '1 Coke (Reg) - DM, 1 French Fries - DM, 1 French Fries Peri Peri - DM', readMore: true },
  { name: 'Triple-treat 2', displayName: 'Add-Ons', items: '1 French Fries - DM, 2 Coke (Reg) - DM' },
  { name: 'Triple-treat 1', displayName: 'Choose Any 1', items: 'Coke (Reg) - DM' },
  { name: 'Add New', displayName: 'Add New', items: '12Pcs Fried Momos - DM, 12Pcs Steamed Momos - DM' },
  { name: 'Chicken tikka addon', displayName: 'Chicken tikka addon', items: 'Chicken tikka addon, curry addon, paneer addon', readMore: true },
  { name: 'Add Choice of Extra Toppings', displayName: 'Add Choice of Extra Toppings', items: 'Corn - A, Extra Cheese, Jalapenos - A', readMore: true },
  { name: 'Choose Your Base', displayName: 'Choose Your Base', items: 'Cheese Burst Base, Standard Base, Thin Crust Base', readMore: true },
  { name: 'Large', displayName: 'Large', items: '-' },
  { name: 'Medium', displayName: 'Medium', items: '-' },
  { name: 'Small', displayName: 'Small', items: '-' },
  { name: 'tub small', displayName: 'tub small', items: '-' },
];

const VARIANTS_DATA = [
  '(Paneer)',
  '(Veg)',
  'Medium',
  'Jain',
  'Regular',
  'Large 14 Inch',
  'Medium 10 Inch',
  'Regular 7 Inch',
  '250gm',
  '1kg',
  '500gm',
  'Phulka 3',
  'Chapati 2',
  'Large',
  'Small',
];
